package com.wangjt.calendar.mysql.dao.model;

public class CalendarUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_user.user_id
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_user.user_addr
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    private String userAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_user.user_mail
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_user.user_tel
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_user.user_name
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_user.user_id
     *
     * @return the value of calendar_user.user_id
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_user.user_id
     *
     * @param userId the value for calendar_user.user_id
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_user.user_addr
     *
     * @return the value of calendar_user.user_addr
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public String getUserAddr() {
        return userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_user.user_addr
     *
     * @param userAddr the value for calendar_user.user_addr
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public void setUserAddr(String userAddr) {
        this.userAddr = userAddr == null ? null : userAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_user.user_mail
     *
     * @return the value of calendar_user.user_mail
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_user.user_mail
     *
     * @param userMail the value for calendar_user.user_mail
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_user.user_tel
     *
     * @return the value of calendar_user.user_tel
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_user.user_tel
     *
     * @param userTel the value for calendar_user.user_tel
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_user.user_name
     *
     * @return the value of calendar_user.user_name
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_user.user_name
     *
     * @param userName the value for calendar_user.user_name
     *
     * @mbggenerated Thu May 03 16:23:51 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}