package com.wangjt.calendar.mysql.dao.model;

public class CalendarType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.ID
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.USER_ID
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.COLOR
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.DESCRIPTION
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.NAME
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.HIDE1
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String hide1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_type.INPUT_DATE
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    private String inputDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.ID
     *
     * @return the value of calendar_type.ID
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.ID
     *
     * @param id the value for calendar_type.ID
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.USER_ID
     *
     * @return the value of calendar_type.USER_ID
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.USER_ID
     *
     * @param userId the value for calendar_type.USER_ID
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.COLOR
     *
     * @return the value of calendar_type.COLOR
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.COLOR
     *
     * @param color the value for calendar_type.COLOR
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.DESCRIPTION
     *
     * @return the value of calendar_type.DESCRIPTION
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.DESCRIPTION
     *
     * @param description the value for calendar_type.DESCRIPTION
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.NAME
     *
     * @return the value of calendar_type.NAME
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.NAME
     *
     * @param name the value for calendar_type.NAME
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.HIDE1
     *
     * @return the value of calendar_type.HIDE1
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getHide1() {
        return hide1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.HIDE1
     *
     * @param hide1 the value for calendar_type.HIDE1
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setHide1(String hide1) {
        this.hide1 = hide1 == null ? null : hide1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_type.INPUT_DATE
     *
     * @return the value of calendar_type.INPUT_DATE
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public String getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_type.INPUT_DATE
     *
     * @param inputDate the value for calendar_type.INPUT_DATE
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    public void setInputDate(String inputDate) {
        this.inputDate = inputDate == null ? null : inputDate.trim();
    }
}