package com.wangjt.calendar.mysql.dao.model;

import java.util.ArrayList;
import java.util.List;

public class CalendarEventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public CalendarEventExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdIsNull() {
            addCriterion("CALENDAR_ID is null");
            return (Criteria) this;
        }

        public Criteria andCalendarIdIsNotNull() {
            addCriterion("CALENDAR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCalendarIdEqualTo(String value) {
            addCriterion("CALENDAR_ID =", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotEqualTo(String value) {
            addCriterion("CALENDAR_ID <>", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdGreaterThan(String value) {
            addCriterion("CALENDAR_ID >", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdGreaterThanOrEqualTo(String value) {
            addCriterion("CALENDAR_ID >=", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdLessThan(String value) {
            addCriterion("CALENDAR_ID <", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdLessThanOrEqualTo(String value) {
            addCriterion("CALENDAR_ID <=", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdLike(String value) {
            addCriterion("CALENDAR_ID like", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotLike(String value) {
            addCriterion("CALENDAR_ID not like", value, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdIn(List<String> values) {
            addCriterion("CALENDAR_ID in", values, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotIn(List<String> values) {
            addCriterion("CALENDAR_ID not in", values, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdBetween(String value1, String value2) {
            addCriterion("CALENDAR_ID between", value1, value2, "calendarId");
            return (Criteria) this;
        }

        public Criteria andCalendarIdNotBetween(String value1, String value2) {
            addCriterion("CALENDAR_ID not between", value1, value2, "calendarId");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeIsNull() {
            addCriterion("REPEAT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeIsNotNull() {
            addCriterion("REPEAT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeEqualTo(String value) {
            addCriterion("REPEAT_TYPE =", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeNotEqualTo(String value) {
            addCriterion("REPEAT_TYPE <>", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeGreaterThan(String value) {
            addCriterion("REPEAT_TYPE >", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REPEAT_TYPE >=", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeLessThan(String value) {
            addCriterion("REPEAT_TYPE <", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeLessThanOrEqualTo(String value) {
            addCriterion("REPEAT_TYPE <=", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeLike(String value) {
            addCriterion("REPEAT_TYPE like", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeNotLike(String value) {
            addCriterion("REPEAT_TYPE not like", value, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeIn(List<String> values) {
            addCriterion("REPEAT_TYPE in", values, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeNotIn(List<String> values) {
            addCriterion("REPEAT_TYPE not in", values, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeBetween(String value1, String value2) {
            addCriterion("REPEAT_TYPE between", value1, value2, "repeatType");
            return (Criteria) this;
        }

        public Criteria andRepeatTypeNotBetween(String value1, String value2) {
            addCriterion("REPEAT_TYPE not between", value1, value2, "repeatType");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(String value) {
            addCriterion("START_TIME =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(String value) {
            addCriterion("START_TIME <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(String value) {
            addCriterion("START_TIME >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("START_TIME >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(String value) {
            addCriterion("START_TIME <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(String value) {
            addCriterion("START_TIME <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLike(String value) {
            addCriterion("START_TIME like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotLike(String value) {
            addCriterion("START_TIME not like", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<String> values) {
            addCriterion("START_TIME in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<String> values) {
            addCriterion("START_TIME not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(String value1, String value2) {
            addCriterion("START_TIME between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(String value1, String value2) {
            addCriterion("START_TIME not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndDayIsNull() {
            addCriterion("END_DAY is null");
            return (Criteria) this;
        }

        public Criteria andEndDayIsNotNull() {
            addCriterion("END_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andEndDayEqualTo(String value) {
            addCriterion("END_DAY =", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotEqualTo(String value) {
            addCriterion("END_DAY <>", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayGreaterThan(String value) {
            addCriterion("END_DAY >", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayGreaterThanOrEqualTo(String value) {
            addCriterion("END_DAY >=", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayLessThan(String value) {
            addCriterion("END_DAY <", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayLessThanOrEqualTo(String value) {
            addCriterion("END_DAY <=", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayLike(String value) {
            addCriterion("END_DAY like", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotLike(String value) {
            addCriterion("END_DAY not like", value, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayIn(List<String> values) {
            addCriterion("END_DAY in", values, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotIn(List<String> values) {
            addCriterion("END_DAY not in", values, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayBetween(String value1, String value2) {
            addCriterion("END_DAY between", value1, value2, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndDayNotBetween(String value1, String value2) {
            addCriterion("END_DAY not between", value1, value2, "endDay");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(String value) {
            addCriterion("END_TIME =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(String value) {
            addCriterion("END_TIME <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(String value) {
            addCriterion("END_TIME >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("END_TIME >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(String value) {
            addCriterion("END_TIME <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(String value) {
            addCriterion("END_TIME <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLike(String value) {
            addCriterion("END_TIME like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotLike(String value) {
            addCriterion("END_TIME not like", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<String> values) {
            addCriterion("END_TIME in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<String> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(String value1, String value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(String value1, String value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("CREATE_DATE like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("CREATE_DATE not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("SUBJECT is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("SUBJECT is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("SUBJECT =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("SUBJECT <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("SUBJECT >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("SUBJECT <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("SUBJECT like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("SUBJECT not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("SUBJECT in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("SUBJECT not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("SUBJECT between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("SUBJECT not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("UPDATE_DATE like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("UPDATE_DATE not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andLocked1IsNull() {
            addCriterion("LOCKED1 is null");
            return (Criteria) this;
        }

        public Criteria andLocked1IsNotNull() {
            addCriterion("LOCKED1 is not null");
            return (Criteria) this;
        }

        public Criteria andLocked1EqualTo(String value) {
            addCriterion("LOCKED1 =", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1NotEqualTo(String value) {
            addCriterion("LOCKED1 <>", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1GreaterThan(String value) {
            addCriterion("LOCKED1 >", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1GreaterThanOrEqualTo(String value) {
            addCriterion("LOCKED1 >=", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1LessThan(String value) {
            addCriterion("LOCKED1 <", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1LessThanOrEqualTo(String value) {
            addCriterion("LOCKED1 <=", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1Like(String value) {
            addCriterion("LOCKED1 like", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1NotLike(String value) {
            addCriterion("LOCKED1 not like", value, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1In(List<String> values) {
            addCriterion("LOCKED1 in", values, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1NotIn(List<String> values) {
            addCriterion("LOCKED1 not in", values, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1Between(String value1, String value2) {
            addCriterion("LOCKED1 between", value1, value2, "locked1");
            return (Criteria) this;
        }

        public Criteria andLocked1NotBetween(String value1, String value2) {
            addCriterion("LOCKED1 not between", value1, value2, "locked1");
            return (Criteria) this;
        }

        public Criteria andLockedIsNull() {
            addCriterion("LOCKED is null");
            return (Criteria) this;
        }

        public Criteria andLockedIsNotNull() {
            addCriterion("LOCKED is not null");
            return (Criteria) this;
        }

        public Criteria andLockedEqualTo(String value) {
            addCriterion("LOCKED =", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotEqualTo(String value) {
            addCriterion("LOCKED <>", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedGreaterThan(String value) {
            addCriterion("LOCKED >", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedGreaterThanOrEqualTo(String value) {
            addCriterion("LOCKED >=", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedLessThan(String value) {
            addCriterion("LOCKED <", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedLessThanOrEqualTo(String value) {
            addCriterion("LOCKED <=", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedLike(String value) {
            addCriterion("LOCKED like", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotLike(String value) {
            addCriterion("LOCKED not like", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedIn(List<String> values) {
            addCriterion("LOCKED in", values, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotIn(List<String> values) {
            addCriterion("LOCKED not in", values, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedBetween(String value1, String value2) {
            addCriterion("LOCKED between", value1, value2, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotBetween(String value1, String value2) {
            addCriterion("LOCKED not between", value1, value2, "locked");
            return (Criteria) this;
        }

        public Criteria andSubEventidIsNull() {
            addCriterion("SUB_EVENTID is null");
            return (Criteria) this;
        }

        public Criteria andSubEventidIsNotNull() {
            addCriterion("SUB_EVENTID is not null");
            return (Criteria) this;
        }

        public Criteria andSubEventidEqualTo(String value) {
            addCriterion("SUB_EVENTID =", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidNotEqualTo(String value) {
            addCriterion("SUB_EVENTID <>", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidGreaterThan(String value) {
            addCriterion("SUB_EVENTID >", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_EVENTID >=", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidLessThan(String value) {
            addCriterion("SUB_EVENTID <", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidLessThanOrEqualTo(String value) {
            addCriterion("SUB_EVENTID <=", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidLike(String value) {
            addCriterion("SUB_EVENTID like", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidNotLike(String value) {
            addCriterion("SUB_EVENTID not like", value, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidIn(List<String> values) {
            addCriterion("SUB_EVENTID in", values, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidNotIn(List<String> values) {
            addCriterion("SUB_EVENTID not in", values, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidBetween(String value1, String value2) {
            addCriterion("SUB_EVENTID between", value1, value2, "subEventid");
            return (Criteria) this;
        }

        public Criteria andSubEventidNotBetween(String value1, String value2) {
            addCriterion("SUB_EVENTID not between", value1, value2, "subEventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidIsNull() {
            addCriterion("YAOQINGEVENTID is null");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidIsNotNull() {
            addCriterion("YAOQINGEVENTID is not null");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidEqualTo(String value) {
            addCriterion("YAOQINGEVENTID =", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidNotEqualTo(String value) {
            addCriterion("YAOQINGEVENTID <>", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidGreaterThan(String value) {
            addCriterion("YAOQINGEVENTID >", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidGreaterThanOrEqualTo(String value) {
            addCriterion("YAOQINGEVENTID >=", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidLessThan(String value) {
            addCriterion("YAOQINGEVENTID <", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidLessThanOrEqualTo(String value) {
            addCriterion("YAOQINGEVENTID <=", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidLike(String value) {
            addCriterion("YAOQINGEVENTID like", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidNotLike(String value) {
            addCriterion("YAOQINGEVENTID not like", value, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidIn(List<String> values) {
            addCriterion("YAOQINGEVENTID in", values, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidNotIn(List<String> values) {
            addCriterion("YAOQINGEVENTID not in", values, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidBetween(String value1, String value2) {
            addCriterion("YAOQINGEVENTID between", value1, value2, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingeventidNotBetween(String value1, String value2) {
            addCriterion("YAOQINGEVENTID not between", value1, value2, "yaoqingeventid");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderIsNull() {
            addCriterion("YAOQINGORDER is null");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderIsNotNull() {
            addCriterion("YAOQINGORDER is not null");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderEqualTo(String value) {
            addCriterion("YAOQINGORDER =", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderNotEqualTo(String value) {
            addCriterion("YAOQINGORDER <>", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderGreaterThan(String value) {
            addCriterion("YAOQINGORDER >", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderGreaterThanOrEqualTo(String value) {
            addCriterion("YAOQINGORDER >=", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderLessThan(String value) {
            addCriterion("YAOQINGORDER <", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderLessThanOrEqualTo(String value) {
            addCriterion("YAOQINGORDER <=", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderLike(String value) {
            addCriterion("YAOQINGORDER like", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderNotLike(String value) {
            addCriterion("YAOQINGORDER not like", value, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderIn(List<String> values) {
            addCriterion("YAOQINGORDER in", values, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderNotIn(List<String> values) {
            addCriterion("YAOQINGORDER not in", values, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderBetween(String value1, String value2) {
            addCriterion("YAOQINGORDER between", value1, value2, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andYaoqingorderNotBetween(String value1, String value2) {
            addCriterion("YAOQINGORDER not between", value1, value2, "yaoqingorder");
            return (Criteria) this;
        }

        public Criteria andIsmanagerIsNull() {
            addCriterion("ISMANAGER is null");
            return (Criteria) this;
        }

        public Criteria andIsmanagerIsNotNull() {
            addCriterion("ISMANAGER is not null");
            return (Criteria) this;
        }

        public Criteria andIsmanagerEqualTo(String value) {
            addCriterion("ISMANAGER =", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerNotEqualTo(String value) {
            addCriterion("ISMANAGER <>", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerGreaterThan(String value) {
            addCriterion("ISMANAGER >", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerGreaterThanOrEqualTo(String value) {
            addCriterion("ISMANAGER >=", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerLessThan(String value) {
            addCriterion("ISMANAGER <", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerLessThanOrEqualTo(String value) {
            addCriterion("ISMANAGER <=", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerLike(String value) {
            addCriterion("ISMANAGER like", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerNotLike(String value) {
            addCriterion("ISMANAGER not like", value, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerIn(List<String> values) {
            addCriterion("ISMANAGER in", values, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerNotIn(List<String> values) {
            addCriterion("ISMANAGER not in", values, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerBetween(String value1, String value2) {
            addCriterion("ISMANAGER between", value1, value2, "ismanager");
            return (Criteria) this;
        }

        public Criteria andIsmanagerNotBetween(String value1, String value2) {
            addCriterion("ISMANAGER not between", value1, value2, "ismanager");
            return (Criteria) this;
        }

        public Criteria andLockedfIsNull() {
            addCriterion("LOCKEDF is null");
            return (Criteria) this;
        }

        public Criteria andLockedfIsNotNull() {
            addCriterion("LOCKEDF is not null");
            return (Criteria) this;
        }

        public Criteria andLockedfEqualTo(String value) {
            addCriterion("LOCKEDF =", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfNotEqualTo(String value) {
            addCriterion("LOCKEDF <>", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfGreaterThan(String value) {
            addCriterion("LOCKEDF >", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfGreaterThanOrEqualTo(String value) {
            addCriterion("LOCKEDF >=", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfLessThan(String value) {
            addCriterion("LOCKEDF <", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfLessThanOrEqualTo(String value) {
            addCriterion("LOCKEDF <=", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfLike(String value) {
            addCriterion("LOCKEDF like", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfNotLike(String value) {
            addCriterion("LOCKEDF not like", value, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfIn(List<String> values) {
            addCriterion("LOCKEDF in", values, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfNotIn(List<String> values) {
            addCriterion("LOCKEDF not in", values, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfBetween(String value1, String value2) {
            addCriterion("LOCKEDF between", value1, value2, "lockedf");
            return (Criteria) this;
        }

        public Criteria andLockedfNotBetween(String value1, String value2) {
            addCriterion("LOCKEDF not between", value1, value2, "lockedf");
            return (Criteria) this;
        }

        public Criteria andYaoqingIsNull() {
            addCriterion("YAOQING is null");
            return (Criteria) this;
        }

        public Criteria andYaoqingIsNotNull() {
            addCriterion("YAOQING is not null");
            return (Criteria) this;
        }

        public Criteria andYaoqingEqualTo(String value) {
            addCriterion("YAOQING =", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingNotEqualTo(String value) {
            addCriterion("YAOQING <>", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingGreaterThan(String value) {
            addCriterion("YAOQING >", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingGreaterThanOrEqualTo(String value) {
            addCriterion("YAOQING >=", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingLessThan(String value) {
            addCriterion("YAOQING <", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingLessThanOrEqualTo(String value) {
            addCriterion("YAOQING <=", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingLike(String value) {
            addCriterion("YAOQING like", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingNotLike(String value) {
            addCriterion("YAOQING not like", value, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingIn(List<String> values) {
            addCriterion("YAOQING in", values, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingNotIn(List<String> values) {
            addCriterion("YAOQING not in", values, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingBetween(String value1, String value2) {
            addCriterion("YAOQING between", value1, value2, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andYaoqingNotBetween(String value1, String value2) {
            addCriterion("YAOQING not between", value1, value2, "yaoqing");
            return (Criteria) this;
        }

        public Criteria andDbflagIsNull() {
            addCriterion("DBFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDbflagIsNotNull() {
            addCriterion("DBFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDbflagEqualTo(String value) {
            addCriterion("DBFLAG =", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagNotEqualTo(String value) {
            addCriterion("DBFLAG <>", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagGreaterThan(String value) {
            addCriterion("DBFLAG >", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagGreaterThanOrEqualTo(String value) {
            addCriterion("DBFLAG >=", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagLessThan(String value) {
            addCriterion("DBFLAG <", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagLessThanOrEqualTo(String value) {
            addCriterion("DBFLAG <=", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagLike(String value) {
            addCriterion("DBFLAG like", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagNotLike(String value) {
            addCriterion("DBFLAG not like", value, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagIn(List<String> values) {
            addCriterion("DBFLAG in", values, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagNotIn(List<String> values) {
            addCriterion("DBFLAG not in", values, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagBetween(String value1, String value2) {
            addCriterion("DBFLAG between", value1, value2, "dbflag");
            return (Criteria) this;
        }

        public Criteria andDbflagNotBetween(String value1, String value2) {
            addCriterion("DBFLAG not between", value1, value2, "dbflag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagIsNull() {
            addCriterion("ALERT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andAlertFlagIsNotNull() {
            addCriterion("ALERT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andAlertFlagEqualTo(String value) {
            addCriterion("ALERT_FLAG =", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagNotEqualTo(String value) {
            addCriterion("ALERT_FLAG <>", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagGreaterThan(String value) {
            addCriterion("ALERT_FLAG >", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ALERT_FLAG >=", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagLessThan(String value) {
            addCriterion("ALERT_FLAG <", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagLessThanOrEqualTo(String value) {
            addCriterion("ALERT_FLAG <=", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagLike(String value) {
            addCriterion("ALERT_FLAG like", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagNotLike(String value) {
            addCriterion("ALERT_FLAG not like", value, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagIn(List<String> values) {
            addCriterion("ALERT_FLAG in", values, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagNotIn(List<String> values) {
            addCriterion("ALERT_FLAG not in", values, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagBetween(String value1, String value2) {
            addCriterion("ALERT_FLAG between", value1, value2, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andAlertFlagNotBetween(String value1, String value2) {
            addCriterion("ALERT_FLAG not between", value1, value2, "alertFlag");
            return (Criteria) this;
        }

        public Criteria andStartDayIsNull() {
            addCriterion("START_DAY is null");
            return (Criteria) this;
        }

        public Criteria andStartDayIsNotNull() {
            addCriterion("START_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andStartDayEqualTo(String value) {
            addCriterion("START_DAY =", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotEqualTo(String value) {
            addCriterion("START_DAY <>", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayGreaterThan(String value) {
            addCriterion("START_DAY >", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayGreaterThanOrEqualTo(String value) {
            addCriterion("START_DAY >=", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLessThan(String value) {
            addCriterion("START_DAY <", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLessThanOrEqualTo(String value) {
            addCriterion("START_DAY <=", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLike(String value) {
            addCriterion("START_DAY like", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotLike(String value) {
            addCriterion("START_DAY not like", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayIn(List<String> values) {
            addCriterion("START_DAY in", values, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotIn(List<String> values) {
            addCriterion("START_DAY not in", values, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayBetween(String value1, String value2) {
            addCriterion("START_DAY between", value1, value2, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotBetween(String value1, String value2) {
            addCriterion("START_DAY not between", value1, value2, "startDay");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_event
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 10 16:52:46 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}