package com.wangjt.calendar.mysql.dao.model;

public class CalendarSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.USER_ID
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.HOUR_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String hourFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.DAY_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String dayFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.WEEK_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String weekFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.FROMTO_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String fromtoFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.ACTIVE_START_TIME
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String activeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.ACTIVE_END_TIME
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String activeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.LANGUAGE
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.INTERVAL_SLOT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String intervalSlot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.START_DAY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String startDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.MONTH_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String monthFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.READ_ONLY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private Integer readOnly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.SINGLE_DAY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private Integer singleDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.HIDE_INACTIVE_ROW
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private Integer hideInactiveRow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.CREATE_BY_DBLCLICK
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private Integer createByDblclick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_setting.INITIAL_VIEW
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    private String initialView;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.USER_ID
     *
     * @return the value of calendar_setting.USER_ID
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.USER_ID
     *
     * @param userId the value for calendar_setting.USER_ID
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.HOUR_FORMAT
     *
     * @return the value of calendar_setting.HOUR_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getHourFormat() {
        return hourFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.HOUR_FORMAT
     *
     * @param hourFormat the value for calendar_setting.HOUR_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setHourFormat(String hourFormat) {
        this.hourFormat = hourFormat == null ? null : hourFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.DAY_FORMAT
     *
     * @return the value of calendar_setting.DAY_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getDayFormat() {
        return dayFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.DAY_FORMAT
     *
     * @param dayFormat the value for calendar_setting.DAY_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setDayFormat(String dayFormat) {
        this.dayFormat = dayFormat == null ? null : dayFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.WEEK_FORMAT
     *
     * @return the value of calendar_setting.WEEK_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getWeekFormat() {
        return weekFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.WEEK_FORMAT
     *
     * @param weekFormat the value for calendar_setting.WEEK_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setWeekFormat(String weekFormat) {
        this.weekFormat = weekFormat == null ? null : weekFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.FROMTO_FORMAT
     *
     * @return the value of calendar_setting.FROMTO_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getFromtoFormat() {
        return fromtoFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.FROMTO_FORMAT
     *
     * @param fromtoFormat the value for calendar_setting.FROMTO_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setFromtoFormat(String fromtoFormat) {
        this.fromtoFormat = fromtoFormat == null ? null : fromtoFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.ACTIVE_START_TIME
     *
     * @return the value of calendar_setting.ACTIVE_START_TIME
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getActiveStartTime() {
        return activeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.ACTIVE_START_TIME
     *
     * @param activeStartTime the value for calendar_setting.ACTIVE_START_TIME
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setActiveStartTime(String activeStartTime) {
        this.activeStartTime = activeStartTime == null ? null : activeStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.ACTIVE_END_TIME
     *
     * @return the value of calendar_setting.ACTIVE_END_TIME
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getActiveEndTime() {
        return activeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.ACTIVE_END_TIME
     *
     * @param activeEndTime the value for calendar_setting.ACTIVE_END_TIME
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setActiveEndTime(String activeEndTime) {
        this.activeEndTime = activeEndTime == null ? null : activeEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.LANGUAGE
     *
     * @return the value of calendar_setting.LANGUAGE
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.LANGUAGE
     *
     * @param language the value for calendar_setting.LANGUAGE
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.INTERVAL_SLOT
     *
     * @return the value of calendar_setting.INTERVAL_SLOT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getIntervalSlot() {
        return intervalSlot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.INTERVAL_SLOT
     *
     * @param intervalSlot the value for calendar_setting.INTERVAL_SLOT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setIntervalSlot(String intervalSlot) {
        this.intervalSlot = intervalSlot == null ? null : intervalSlot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.START_DAY
     *
     * @return the value of calendar_setting.START_DAY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getStartDay() {
        return startDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.START_DAY
     *
     * @param startDay the value for calendar_setting.START_DAY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setStartDay(String startDay) {
        this.startDay = startDay == null ? null : startDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.MONTH_FORMAT
     *
     * @return the value of calendar_setting.MONTH_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getMonthFormat() {
        return monthFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.MONTH_FORMAT
     *
     * @param monthFormat the value for calendar_setting.MONTH_FORMAT
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setMonthFormat(String monthFormat) {
        this.monthFormat = monthFormat == null ? null : monthFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.READ_ONLY
     *
     * @return the value of calendar_setting.READ_ONLY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Integer getReadOnly() {
        return readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.READ_ONLY
     *
     * @param readOnly the value for calendar_setting.READ_ONLY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setReadOnly(Integer readOnly) {
        this.readOnly = readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.SINGLE_DAY
     *
     * @return the value of calendar_setting.SINGLE_DAY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Integer getSingleDay() {
        return singleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.SINGLE_DAY
     *
     * @param singleDay the value for calendar_setting.SINGLE_DAY
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setSingleDay(Integer singleDay) {
        this.singleDay = singleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.HIDE_INACTIVE_ROW
     *
     * @return the value of calendar_setting.HIDE_INACTIVE_ROW
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Integer getHideInactiveRow() {
        return hideInactiveRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.HIDE_INACTIVE_ROW
     *
     * @param hideInactiveRow the value for calendar_setting.HIDE_INACTIVE_ROW
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setHideInactiveRow(Integer hideInactiveRow) {
        this.hideInactiveRow = hideInactiveRow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.CREATE_BY_DBLCLICK
     *
     * @return the value of calendar_setting.CREATE_BY_DBLCLICK
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Integer getCreateByDblclick() {
        return createByDblclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.CREATE_BY_DBLCLICK
     *
     * @param createByDblclick the value for calendar_setting.CREATE_BY_DBLCLICK
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setCreateByDblclick(Integer createByDblclick) {
        this.createByDblclick = createByDblclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_setting.INITIAL_VIEW
     *
     * @return the value of calendar_setting.INITIAL_VIEW
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getInitialView() {
        return initialView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_setting.INITIAL_VIEW
     *
     * @param initialView the value for calendar_setting.INITIAL_VIEW
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setInitialView(String initialView) {
        this.initialView = initialView == null ? null : initialView.trim();
    }
}