package com.wangjt.calendar.mysql.dao.model;

public class CalendarMd5 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.signature
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.flag
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.app_secret
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.app_id
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.timestamp
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.user_id
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.nonceStr
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private String noncestr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar_md5.databyte
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    private byte[] databyte;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.signature
     *
     * @return the value of calendar_md5.signature
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.signature
     *
     * @param signature the value for calendar_md5.signature
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.flag
     *
     * @return the value of calendar_md5.flag
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.flag
     *
     * @param flag the value for calendar_md5.flag
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.app_secret
     *
     * @return the value of calendar_md5.app_secret
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.app_secret
     *
     * @param appSecret the value for calendar_md5.app_secret
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.app_id
     *
     * @return the value of calendar_md5.app_id
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.app_id
     *
     * @param appId the value for calendar_md5.app_id
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.timestamp
     *
     * @return the value of calendar_md5.timestamp
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.timestamp
     *
     * @param timestamp the value for calendar_md5.timestamp
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.user_id
     *
     * @return the value of calendar_md5.user_id
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.user_id
     *
     * @param userId the value for calendar_md5.user_id
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.nonceStr
     *
     * @return the value of calendar_md5.nonceStr
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public String getNoncestr() {
        return noncestr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.nonceStr
     *
     * @param noncestr the value for calendar_md5.nonceStr
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setNoncestr(String noncestr) {
        this.noncestr = noncestr == null ? null : noncestr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar_md5.databyte
     *
     * @return the value of calendar_md5.databyte
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public byte[] getDatabyte() {
        return databyte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar_md5.databyte
     *
     * @param databyte the value for calendar_md5.databyte
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    public void setDatabyte(byte[] databyte) {
        this.databyte = databyte;
    }
}