package com.wangjt.calendar.mysql.dao.model;

import java.util.ArrayList;
import java.util.List;

public class CalendarSettingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public CalendarSettingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andHourFormatIsNull() {
            addCriterion("HOUR_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andHourFormatIsNotNull() {
            addCriterion("HOUR_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andHourFormatEqualTo(String value) {
            addCriterion("HOUR_FORMAT =", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatNotEqualTo(String value) {
            addCriterion("HOUR_FORMAT <>", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatGreaterThan(String value) {
            addCriterion("HOUR_FORMAT >", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatGreaterThanOrEqualTo(String value) {
            addCriterion("HOUR_FORMAT >=", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatLessThan(String value) {
            addCriterion("HOUR_FORMAT <", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatLessThanOrEqualTo(String value) {
            addCriterion("HOUR_FORMAT <=", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatLike(String value) {
            addCriterion("HOUR_FORMAT like", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatNotLike(String value) {
            addCriterion("HOUR_FORMAT not like", value, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatIn(List<String> values) {
            addCriterion("HOUR_FORMAT in", values, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatNotIn(List<String> values) {
            addCriterion("HOUR_FORMAT not in", values, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatBetween(String value1, String value2) {
            addCriterion("HOUR_FORMAT between", value1, value2, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andHourFormatNotBetween(String value1, String value2) {
            addCriterion("HOUR_FORMAT not between", value1, value2, "hourFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatIsNull() {
            addCriterion("DAY_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andDayFormatIsNotNull() {
            addCriterion("DAY_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andDayFormatEqualTo(String value) {
            addCriterion("DAY_FORMAT =", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatNotEqualTo(String value) {
            addCriterion("DAY_FORMAT <>", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatGreaterThan(String value) {
            addCriterion("DAY_FORMAT >", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatGreaterThanOrEqualTo(String value) {
            addCriterion("DAY_FORMAT >=", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatLessThan(String value) {
            addCriterion("DAY_FORMAT <", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatLessThanOrEqualTo(String value) {
            addCriterion("DAY_FORMAT <=", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatLike(String value) {
            addCriterion("DAY_FORMAT like", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatNotLike(String value) {
            addCriterion("DAY_FORMAT not like", value, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatIn(List<String> values) {
            addCriterion("DAY_FORMAT in", values, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatNotIn(List<String> values) {
            addCriterion("DAY_FORMAT not in", values, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatBetween(String value1, String value2) {
            addCriterion("DAY_FORMAT between", value1, value2, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andDayFormatNotBetween(String value1, String value2) {
            addCriterion("DAY_FORMAT not between", value1, value2, "dayFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatIsNull() {
            addCriterion("WEEK_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andWeekFormatIsNotNull() {
            addCriterion("WEEK_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andWeekFormatEqualTo(String value) {
            addCriterion("WEEK_FORMAT =", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatNotEqualTo(String value) {
            addCriterion("WEEK_FORMAT <>", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatGreaterThan(String value) {
            addCriterion("WEEK_FORMAT >", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatGreaterThanOrEqualTo(String value) {
            addCriterion("WEEK_FORMAT >=", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatLessThan(String value) {
            addCriterion("WEEK_FORMAT <", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatLessThanOrEqualTo(String value) {
            addCriterion("WEEK_FORMAT <=", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatLike(String value) {
            addCriterion("WEEK_FORMAT like", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatNotLike(String value) {
            addCriterion("WEEK_FORMAT not like", value, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatIn(List<String> values) {
            addCriterion("WEEK_FORMAT in", values, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatNotIn(List<String> values) {
            addCriterion("WEEK_FORMAT not in", values, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatBetween(String value1, String value2) {
            addCriterion("WEEK_FORMAT between", value1, value2, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andWeekFormatNotBetween(String value1, String value2) {
            addCriterion("WEEK_FORMAT not between", value1, value2, "weekFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatIsNull() {
            addCriterion("FROMTO_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatIsNotNull() {
            addCriterion("FROMTO_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatEqualTo(String value) {
            addCriterion("FROMTO_FORMAT =", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatNotEqualTo(String value) {
            addCriterion("FROMTO_FORMAT <>", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatGreaterThan(String value) {
            addCriterion("FROMTO_FORMAT >", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatGreaterThanOrEqualTo(String value) {
            addCriterion("FROMTO_FORMAT >=", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatLessThan(String value) {
            addCriterion("FROMTO_FORMAT <", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatLessThanOrEqualTo(String value) {
            addCriterion("FROMTO_FORMAT <=", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatLike(String value) {
            addCriterion("FROMTO_FORMAT like", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatNotLike(String value) {
            addCriterion("FROMTO_FORMAT not like", value, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatIn(List<String> values) {
            addCriterion("FROMTO_FORMAT in", values, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatNotIn(List<String> values) {
            addCriterion("FROMTO_FORMAT not in", values, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatBetween(String value1, String value2) {
            addCriterion("FROMTO_FORMAT between", value1, value2, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andFromtoFormatNotBetween(String value1, String value2) {
            addCriterion("FROMTO_FORMAT not between", value1, value2, "fromtoFormat");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeIsNull() {
            addCriterion("ACTIVE_START_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeIsNotNull() {
            addCriterion("ACTIVE_START_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeEqualTo(String value) {
            addCriterion("ACTIVE_START_TIME =", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotEqualTo(String value) {
            addCriterion("ACTIVE_START_TIME <>", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeGreaterThan(String value) {
            addCriterion("ACTIVE_START_TIME >", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_START_TIME >=", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeLessThan(String value) {
            addCriterion("ACTIVE_START_TIME <", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_START_TIME <=", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeLike(String value) {
            addCriterion("ACTIVE_START_TIME like", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotLike(String value) {
            addCriterion("ACTIVE_START_TIME not like", value, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeIn(List<String> values) {
            addCriterion("ACTIVE_START_TIME in", values, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotIn(List<String> values) {
            addCriterion("ACTIVE_START_TIME not in", values, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeBetween(String value1, String value2) {
            addCriterion("ACTIVE_START_TIME between", value1, value2, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveStartTimeNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_START_TIME not between", value1, value2, "activeStartTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeIsNull() {
            addCriterion("ACTIVE_END_TIME is null");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeIsNotNull() {
            addCriterion("ACTIVE_END_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeEqualTo(String value) {
            addCriterion("ACTIVE_END_TIME =", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotEqualTo(String value) {
            addCriterion("ACTIVE_END_TIME <>", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeGreaterThan(String value) {
            addCriterion("ACTIVE_END_TIME >", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTIVE_END_TIME >=", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeLessThan(String value) {
            addCriterion("ACTIVE_END_TIME <", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeLessThanOrEqualTo(String value) {
            addCriterion("ACTIVE_END_TIME <=", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeLike(String value) {
            addCriterion("ACTIVE_END_TIME like", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotLike(String value) {
            addCriterion("ACTIVE_END_TIME not like", value, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeIn(List<String> values) {
            addCriterion("ACTIVE_END_TIME in", values, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotIn(List<String> values) {
            addCriterion("ACTIVE_END_TIME not in", values, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeBetween(String value1, String value2) {
            addCriterion("ACTIVE_END_TIME between", value1, value2, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andActiveEndTimeNotBetween(String value1, String value2) {
            addCriterion("ACTIVE_END_TIME not between", value1, value2, "activeEndTime");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("LANGUAGE is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("LANGUAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("LANGUAGE =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("LANGUAGE <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("LANGUAGE >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("LANGUAGE >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("LANGUAGE <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("LANGUAGE <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("LANGUAGE like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("LANGUAGE not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("LANGUAGE in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("LANGUAGE not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("LANGUAGE between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("LANGUAGE not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotIsNull() {
            addCriterion("INTERVAL_SLOT is null");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotIsNotNull() {
            addCriterion("INTERVAL_SLOT is not null");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotEqualTo(String value) {
            addCriterion("INTERVAL_SLOT =", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotNotEqualTo(String value) {
            addCriterion("INTERVAL_SLOT <>", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotGreaterThan(String value) {
            addCriterion("INTERVAL_SLOT >", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotGreaterThanOrEqualTo(String value) {
            addCriterion("INTERVAL_SLOT >=", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotLessThan(String value) {
            addCriterion("INTERVAL_SLOT <", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotLessThanOrEqualTo(String value) {
            addCriterion("INTERVAL_SLOT <=", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotLike(String value) {
            addCriterion("INTERVAL_SLOT like", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotNotLike(String value) {
            addCriterion("INTERVAL_SLOT not like", value, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotIn(List<String> values) {
            addCriterion("INTERVAL_SLOT in", values, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotNotIn(List<String> values) {
            addCriterion("INTERVAL_SLOT not in", values, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotBetween(String value1, String value2) {
            addCriterion("INTERVAL_SLOT between", value1, value2, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andIntervalSlotNotBetween(String value1, String value2) {
            addCriterion("INTERVAL_SLOT not between", value1, value2, "intervalSlot");
            return (Criteria) this;
        }

        public Criteria andStartDayIsNull() {
            addCriterion("START_DAY is null");
            return (Criteria) this;
        }

        public Criteria andStartDayIsNotNull() {
            addCriterion("START_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andStartDayEqualTo(String value) {
            addCriterion("START_DAY =", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotEqualTo(String value) {
            addCriterion("START_DAY <>", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayGreaterThan(String value) {
            addCriterion("START_DAY >", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayGreaterThanOrEqualTo(String value) {
            addCriterion("START_DAY >=", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLessThan(String value) {
            addCriterion("START_DAY <", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLessThanOrEqualTo(String value) {
            addCriterion("START_DAY <=", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayLike(String value) {
            addCriterion("START_DAY like", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotLike(String value) {
            addCriterion("START_DAY not like", value, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayIn(List<String> values) {
            addCriterion("START_DAY in", values, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotIn(List<String> values) {
            addCriterion("START_DAY not in", values, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayBetween(String value1, String value2) {
            addCriterion("START_DAY between", value1, value2, "startDay");
            return (Criteria) this;
        }

        public Criteria andStartDayNotBetween(String value1, String value2) {
            addCriterion("START_DAY not between", value1, value2, "startDay");
            return (Criteria) this;
        }

        public Criteria andMonthFormatIsNull() {
            addCriterion("MONTH_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andMonthFormatIsNotNull() {
            addCriterion("MONTH_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andMonthFormatEqualTo(String value) {
            addCriterion("MONTH_FORMAT =", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatNotEqualTo(String value) {
            addCriterion("MONTH_FORMAT <>", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatGreaterThan(String value) {
            addCriterion("MONTH_FORMAT >", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatGreaterThanOrEqualTo(String value) {
            addCriterion("MONTH_FORMAT >=", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatLessThan(String value) {
            addCriterion("MONTH_FORMAT <", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatLessThanOrEqualTo(String value) {
            addCriterion("MONTH_FORMAT <=", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatLike(String value) {
            addCriterion("MONTH_FORMAT like", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatNotLike(String value) {
            addCriterion("MONTH_FORMAT not like", value, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatIn(List<String> values) {
            addCriterion("MONTH_FORMAT in", values, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatNotIn(List<String> values) {
            addCriterion("MONTH_FORMAT not in", values, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatBetween(String value1, String value2) {
            addCriterion("MONTH_FORMAT between", value1, value2, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andMonthFormatNotBetween(String value1, String value2) {
            addCriterion("MONTH_FORMAT not between", value1, value2, "monthFormat");
            return (Criteria) this;
        }

        public Criteria andReadOnlyIsNull() {
            addCriterion("READ_ONLY is null");
            return (Criteria) this;
        }

        public Criteria andReadOnlyIsNotNull() {
            addCriterion("READ_ONLY is not null");
            return (Criteria) this;
        }

        public Criteria andReadOnlyEqualTo(Integer value) {
            addCriterion("READ_ONLY =", value, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyNotEqualTo(Integer value) {
            addCriterion("READ_ONLY <>", value, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyGreaterThan(Integer value) {
            addCriterion("READ_ONLY >", value, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyGreaterThanOrEqualTo(Integer value) {
            addCriterion("READ_ONLY >=", value, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyLessThan(Integer value) {
            addCriterion("READ_ONLY <", value, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyLessThanOrEqualTo(Integer value) {
            addCriterion("READ_ONLY <=", value, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyIn(List<Integer> values) {
            addCriterion("READ_ONLY in", values, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyNotIn(List<Integer> values) {
            addCriterion("READ_ONLY not in", values, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyBetween(Integer value1, Integer value2) {
            addCriterion("READ_ONLY between", value1, value2, "readOnly");
            return (Criteria) this;
        }

        public Criteria andReadOnlyNotBetween(Integer value1, Integer value2) {
            addCriterion("READ_ONLY not between", value1, value2, "readOnly");
            return (Criteria) this;
        }

        public Criteria andSingleDayIsNull() {
            addCriterion("SINGLE_DAY is null");
            return (Criteria) this;
        }

        public Criteria andSingleDayIsNotNull() {
            addCriterion("SINGLE_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andSingleDayEqualTo(Integer value) {
            addCriterion("SINGLE_DAY =", value, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayNotEqualTo(Integer value) {
            addCriterion("SINGLE_DAY <>", value, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayGreaterThan(Integer value) {
            addCriterion("SINGLE_DAY >", value, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("SINGLE_DAY >=", value, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayLessThan(Integer value) {
            addCriterion("SINGLE_DAY <", value, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayLessThanOrEqualTo(Integer value) {
            addCriterion("SINGLE_DAY <=", value, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayIn(List<Integer> values) {
            addCriterion("SINGLE_DAY in", values, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayNotIn(List<Integer> values) {
            addCriterion("SINGLE_DAY not in", values, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayBetween(Integer value1, Integer value2) {
            addCriterion("SINGLE_DAY between", value1, value2, "singleDay");
            return (Criteria) this;
        }

        public Criteria andSingleDayNotBetween(Integer value1, Integer value2) {
            addCriterion("SINGLE_DAY not between", value1, value2, "singleDay");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowIsNull() {
            addCriterion("HIDE_INACTIVE_ROW is null");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowIsNotNull() {
            addCriterion("HIDE_INACTIVE_ROW is not null");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowEqualTo(Integer value) {
            addCriterion("HIDE_INACTIVE_ROW =", value, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowNotEqualTo(Integer value) {
            addCriterion("HIDE_INACTIVE_ROW <>", value, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowGreaterThan(Integer value) {
            addCriterion("HIDE_INACTIVE_ROW >", value, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowGreaterThanOrEqualTo(Integer value) {
            addCriterion("HIDE_INACTIVE_ROW >=", value, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowLessThan(Integer value) {
            addCriterion("HIDE_INACTIVE_ROW <", value, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowLessThanOrEqualTo(Integer value) {
            addCriterion("HIDE_INACTIVE_ROW <=", value, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowIn(List<Integer> values) {
            addCriterion("HIDE_INACTIVE_ROW in", values, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowNotIn(List<Integer> values) {
            addCriterion("HIDE_INACTIVE_ROW not in", values, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowBetween(Integer value1, Integer value2) {
            addCriterion("HIDE_INACTIVE_ROW between", value1, value2, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andHideInactiveRowNotBetween(Integer value1, Integer value2) {
            addCriterion("HIDE_INACTIVE_ROW not between", value1, value2, "hideInactiveRow");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickIsNull() {
            addCriterion("CREATE_BY_DBLCLICK is null");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickIsNotNull() {
            addCriterion("CREATE_BY_DBLCLICK is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickEqualTo(Integer value) {
            addCriterion("CREATE_BY_DBLCLICK =", value, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickNotEqualTo(Integer value) {
            addCriterion("CREATE_BY_DBLCLICK <>", value, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickGreaterThan(Integer value) {
            addCriterion("CREATE_BY_DBLCLICK >", value, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATE_BY_DBLCLICK >=", value, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickLessThan(Integer value) {
            addCriterion("CREATE_BY_DBLCLICK <", value, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickLessThanOrEqualTo(Integer value) {
            addCriterion("CREATE_BY_DBLCLICK <=", value, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickIn(List<Integer> values) {
            addCriterion("CREATE_BY_DBLCLICK in", values, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickNotIn(List<Integer> values) {
            addCriterion("CREATE_BY_DBLCLICK not in", values, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_BY_DBLCLICK between", value1, value2, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andCreateByDblclickNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATE_BY_DBLCLICK not between", value1, value2, "createByDblclick");
            return (Criteria) this;
        }

        public Criteria andInitialViewIsNull() {
            addCriterion("INITIAL_VIEW is null");
            return (Criteria) this;
        }

        public Criteria andInitialViewIsNotNull() {
            addCriterion("INITIAL_VIEW is not null");
            return (Criteria) this;
        }

        public Criteria andInitialViewEqualTo(String value) {
            addCriterion("INITIAL_VIEW =", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewNotEqualTo(String value) {
            addCriterion("INITIAL_VIEW <>", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewGreaterThan(String value) {
            addCriterion("INITIAL_VIEW >", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewGreaterThanOrEqualTo(String value) {
            addCriterion("INITIAL_VIEW >=", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewLessThan(String value) {
            addCriterion("INITIAL_VIEW <", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewLessThanOrEqualTo(String value) {
            addCriterion("INITIAL_VIEW <=", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewLike(String value) {
            addCriterion("INITIAL_VIEW like", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewNotLike(String value) {
            addCriterion("INITIAL_VIEW not like", value, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewIn(List<String> values) {
            addCriterion("INITIAL_VIEW in", values, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewNotIn(List<String> values) {
            addCriterion("INITIAL_VIEW not in", values, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewBetween(String value1, String value2) {
            addCriterion("INITIAL_VIEW between", value1, value2, "initialView");
            return (Criteria) this;
        }

        public Criteria andInitialViewNotBetween(String value1, String value2) {
            addCriterion("INITIAL_VIEW not between", value1, value2, "initialView");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_setting
     *
     * @mbggenerated do_not_delete_during_merge Tue Apr 10 16:52:46 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}