package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarMd5;
import com.wangjt.calendar.mysql.dao.model.CalendarMd5Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarMd5Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int countByExample(CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int deleteByExample(CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int deleteByPrimaryKey(String signature);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int insert(CalendarMd5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int insertSelective(CalendarMd5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    List<CalendarMd5> selectByExampleWithBLOBs(CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    List<CalendarMd5> selectByExample(CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    CalendarMd5 selectByPrimaryKey(String signature);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") CalendarMd5 record, @Param("example") CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CalendarMd5 record, @Param("example") CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int updateByExample(@Param("record") CalendarMd5 record, @Param("example") CalendarMd5Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int updateByPrimaryKeySelective(CalendarMd5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(CalendarMd5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_md5
     *
     * @mbggenerated Fri Apr 20 10:13:22 CST 2018
     */
    int updateByPrimaryKey(CalendarMd5 record);
}