package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarEmailEvent;
import com.wangjt.calendar.mysql.dao.model.CalendarEmailEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarEmailEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    int countByExample(CalendarEmailEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    int deleteByExample(CalendarEmailEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    int insert(CalendarEmailEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    int insertSelective(CalendarEmailEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    List<CalendarEmailEvent> selectByExample(CalendarEmailEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") CalendarEmailEvent record, @Param("example") CalendarEmailEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_email_event
     *
     * @mbggenerated Thu May 03 16:56:10 CST 2018
     */
    int updateByExample(@Param("record") CalendarEmailEvent record, @Param("example") CalendarEmailEventExample example);
}