package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarSetting;
import com.wangjt.calendar.mysql.dao.model.CalendarSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int countByExample(CalendarSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int deleteByExample(CalendarSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int insert(CalendarSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int insertSelective(CalendarSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    List<CalendarSetting> selectByExample(CalendarSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    CalendarSetting selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") CalendarSetting record, @Param("example") CalendarSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByExample(@Param("record") CalendarSetting record, @Param("example") CalendarSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByPrimaryKeySelective(CalendarSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_setting
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByPrimaryKey(CalendarSetting record);
}