package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarEventReminder;
import com.wangjt.calendar.mysql.dao.model.CalendarEventReminderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarEventReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    int countByExample(CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    int deleteByExample(CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    int insert(CalendarEventReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    int insertSelective(CalendarEventReminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    List<CalendarEventReminder> selectByExample(CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") CalendarEventReminder record, @Param("example") CalendarEventReminderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event_reminder
     *
     * @mbggenerated Mon Apr 09 10:08:15 CST 2018
     */
    int updateByExample(@Param("record") CalendarEventReminder record, @Param("example") CalendarEventReminderExample example);
}