package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarType;
import com.wangjt.calendar.mysql.dao.model.CalendarTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int countByExample(CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int deleteByExample(CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int insert(CalendarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int insertSelective(CalendarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    List<CalendarType> selectByExample(CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    CalendarType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") CalendarType record, @Param("example") CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int updateByExample(@Param("record") CalendarType record, @Param("example") CalendarTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int updateByPrimaryKeySelective(CalendarType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_type
     *
     * @mbggenerated Wed Apr 04 17:19:56 CST 2018
     */
    int updateByPrimaryKey(CalendarType record);
}