package com.wangjt.calendar.mysql.dao.mapper;

import com.wangjt.calendar.mysql.dao.model.CalendarEvent;
import com.wangjt.calendar.mysql.dao.model.CalendarEventExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalendarEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int countByExample(CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int deleteByExample(CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int insert(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int insertSelective(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    List<CalendarEvent> selectByExample(CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    CalendarEvent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") CalendarEvent record, @Param("example") CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByExample(@Param("record") CalendarEvent record, @Param("example") CalendarEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByPrimaryKeySelective(CalendarEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar_event
     *
     * @mbggenerated Tue Apr 10 16:52:46 CST 2018
     */
    int updateByPrimaryKey(CalendarEvent record);
}